/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarEmailRouteImport } from './routes/verificar-email'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as EmailPendenteRouteImport } from './routes/email-pendente'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as AppTreinosRouteImport } from './routes/app.treinos'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppNutricaoRouteImport } from './routes/app.nutricao'
import { Route as AppExerciciosRouteImport } from './routes/app.exercicios'
import { Route as AppCorpoRouteImport } from './routes/app.corpo'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as ApiVerifyEmailLinkRouteImport } from './routes/api/verify-email-link'
import { Route as ApiVerifyCodeRouteImport } from './routes/api/verify-code'
import { Route as ApiSendVerificationRouteImport } from './routes/api/send-verification'
import { Route as ApiMealPlanRouteImport } from './routes/api/meal-plan'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat-stream'
import { Route as ApiAnalyzeImageRouteImport } from './routes/api/analyze-image'
import { Route as ApiAiWorkoutRouteImport } from './routes/api/ai-workout'
import { Route as AppTreinoIdRouteImport } from './routes/app.treino.$id'
import { Route as AppHistoricoIdRouteImport } from './routes/app.historico.$id'
import { Route as AppExercicioIdRouteImport } from './routes/app.exercicio.$id'

const VerificarEmailRoute = VerificarEmailRouteImport.update({
  id: '/verificar-email',
  path: '/verificar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailPendenteRoute = EmailPendenteRouteImport.update({
  id: '/email-pendente',
  path: '/email-pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppTreinosRoute = AppTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNutricaoRoute = AppNutricaoRouteImport.update({
  id: '/nutricao',
  path: '/nutricao',
  getParentRoute: () => AppRoute,
} as any)
const AppExerciciosRoute = AppExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => AppRoute,
} as any)
const AppCorpoRoute = AppCorpoRouteImport.update({
  id: '/corpo',
  path: '/corpo',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiVerifyEmailLinkRoute = ApiVerifyEmailLinkRouteImport.update({
  id: '/api/verify-email-link',
  path: '/api/verify-email-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyCodeRoute = ApiVerifyCodeRouteImport.update({
  id: '/api/verify-code',
  path: '/api/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendVerificationRoute = ApiSendVerificationRouteImport.update({
  id: '/api/send-verification',
  path: '/api/send-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMealPlanRoute = ApiMealPlanRouteImport.update({
  id: '/api/meal-plan',
  path: '/api/meal-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat-stream',
  path: '/api/chat-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeImageRoute = ApiAnalyzeImageRouteImport.update({
  id: '/api/analyze-image',
  path: '/api/analyze-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiWorkoutRoute = ApiAiWorkoutRouteImport.update({
  id: '/api/ai-workout',
  path: '/api/ai-workout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTreinoIdRoute = AppTreinoIdRouteImport.update({
  id: '/treino/$id',
  path: '/treino/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoIdRoute = AppHistoricoIdRouteImport.update({
  id: '/historico/$id',
  path: '/historico/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppExercicioIdRoute = AppExercicioIdRouteImport.update({
  id: '/exercicio/$id',
  path: '/exercicio/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/criar-conta': typeof CriarContaRoute
  '/email-pendente': typeof EmailPendenteRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/paywall': typeof PaywallRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/termos': typeof TermosRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/api/ai-workout': typeof ApiAiWorkoutRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/meal-plan': typeof ApiMealPlanRoute
  '/api/send-verification': typeof ApiSendVerificationRoute
  '/api/verify-code': typeof ApiVerifyCodeRoute
  '/api/verify-email-link': typeof ApiVerifyEmailLinkRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/corpo': typeof AppCorpoRoute
  '/app/exercicios': typeof AppExerciciosRoute
  '/app/nutricao': typeof AppNutricaoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/treinos': typeof AppTreinosRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/app/exercicio/$id': typeof AppExercicioIdRoute
  '/app/historico/$id': typeof AppHistoricoIdRoute
  '/app/treino/$id': typeof AppTreinoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/email-pendente': typeof EmailPendenteRoute
  '/landing': typeof LandingRoute
  '/paywall': typeof PaywallRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/termos': typeof TermosRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/api/ai-workout': typeof ApiAiWorkoutRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/meal-plan': typeof ApiMealPlanRoute
  '/api/send-verification': typeof ApiSendVerificationRoute
  '/api/verify-code': typeof ApiVerifyCodeRoute
  '/api/verify-email-link': typeof ApiVerifyEmailLinkRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/corpo': typeof AppCorpoRoute
  '/app/exercicios': typeof AppExerciciosRoute
  '/app/nutricao': typeof AppNutricaoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/treinos': typeof AppTreinosRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/app': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/app/exercicio/$id': typeof AppExercicioIdRoute
  '/app/historico/$id': typeof AppHistoricoIdRoute
  '/app/treino/$id': typeof AppTreinoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/criar-conta': typeof CriarContaRoute
  '/email-pendente': typeof EmailPendenteRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/paywall': typeof PaywallRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/termos': typeof TermosRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/api/ai-workout': typeof ApiAiWorkoutRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/meal-plan': typeof ApiMealPlanRoute
  '/api/send-verification': typeof ApiSendVerificationRoute
  '/api/verify-code': typeof ApiVerifyCodeRoute
  '/api/verify-email-link': typeof ApiVerifyEmailLinkRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/corpo': typeof AppCorpoRoute
  '/app/exercicios': typeof AppExerciciosRoute
  '/app/nutricao': typeof AppNutricaoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/treinos': typeof AppTreinosRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/app/exercicio/$id': typeof AppExercicioIdRoute
  '/app/historico/$id': typeof AppHistoricoIdRoute
  '/app/treino/$id': typeof AppTreinoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/criar-conta'
    | '/email-pendente'
    | '/landing'
    | '/onboarding'
    | '/paywall'
    | '/privacidade'
    | '/recuperar-senha'
    | '/termos'
    | '/verificar-email'
    | '/api/ai-workout'
    | '/api/analyze-image'
    | '/api/chat-stream'
    | '/api/meal-plan'
    | '/api/send-verification'
    | '/api/verify-code'
    | '/api/verify-email-link'
    | '/app/analytics'
    | '/app/configuracoes'
    | '/app/corpo'
    | '/app/exercicios'
    | '/app/nutricao'
    | '/app/perfil'
    | '/app/treinos'
    | '/onboarding/$step'
    | '/app/'
    | '/onboarding/'
    | '/app/exercicio/$id'
    | '/app/historico/$id'
    | '/app/treino/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar-conta'
    | '/email-pendente'
    | '/landing'
    | '/paywall'
    | '/privacidade'
    | '/recuperar-senha'
    | '/termos'
    | '/verificar-email'
    | '/api/ai-workout'
    | '/api/analyze-image'
    | '/api/chat-stream'
    | '/api/meal-plan'
    | '/api/send-verification'
    | '/api/verify-code'
    | '/api/verify-email-link'
    | '/app/analytics'
    | '/app/configuracoes'
    | '/app/corpo'
    | '/app/exercicios'
    | '/app/nutricao'
    | '/app/perfil'
    | '/app/treinos'
    | '/onboarding/$step'
    | '/app'
    | '/onboarding'
    | '/app/exercicio/$id'
    | '/app/historico/$id'
    | '/app/treino/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/criar-conta'
    | '/email-pendente'
    | '/landing'
    | '/onboarding'
    | '/paywall'
    | '/privacidade'
    | '/recuperar-senha'
    | '/termos'
    | '/verificar-email'
    | '/api/ai-workout'
    | '/api/analyze-image'
    | '/api/chat-stream'
    | '/api/meal-plan'
    | '/api/send-verification'
    | '/api/verify-code'
    | '/api/verify-email-link'
    | '/app/analytics'
    | '/app/configuracoes'
    | '/app/corpo'
    | '/app/exercicios'
    | '/app/nutricao'
    | '/app/perfil'
    | '/app/treinos'
    | '/onboarding/$step'
    | '/app/'
    | '/onboarding/'
    | '/app/exercicio/$id'
    | '/app/historico/$id'
    | '/app/treino/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CriarContaRoute: typeof CriarContaRoute
  EmailPendenteRoute: typeof EmailPendenteRoute
  LandingRoute: typeof LandingRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PaywallRoute: typeof PaywallRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  TermosRoute: typeof TermosRoute
  VerificarEmailRoute: typeof VerificarEmailRoute
  ApiAiWorkoutRoute: typeof ApiAiWorkoutRoute
  ApiAnalyzeImageRoute: typeof ApiAnalyzeImageRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ApiMealPlanRoute: typeof ApiMealPlanRoute
  ApiSendVerificationRoute: typeof ApiSendVerificationRoute
  ApiVerifyCodeRoute: typeof ApiVerifyCodeRoute
  ApiVerifyEmailLinkRoute: typeof ApiVerifyEmailLinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar-email': {
      id: '/verificar-email'
      path: '/verificar-email'
      fullPath: '/verificar-email'
      preLoaderRoute: typeof VerificarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-pendente': {
      id: '/email-pendente'
      path: '/email-pendente'
      fullPath: '/email-pendente'
      preLoaderRoute: typeof EmailPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/treinos': {
      id: '/app/treinos'
      path: '/treinos'
      fullPath: '/app/treinos'
      preLoaderRoute: typeof AppTreinosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nutricao': {
      id: '/app/nutricao'
      path: '/nutricao'
      fullPath: '/app/nutricao'
      preLoaderRoute: typeof AppNutricaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exercicios': {
      id: '/app/exercicios'
      path: '/exercicios'
      fullPath: '/app/exercicios'
      preLoaderRoute: typeof AppExerciciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/corpo': {
      id: '/app/corpo'
      path: '/corpo'
      fullPath: '/app/corpo'
      preLoaderRoute: typeof AppCorpoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/verify-email-link': {
      id: '/api/verify-email-link'
      path: '/api/verify-email-link'
      fullPath: '/api/verify-email-link'
      preLoaderRoute: typeof ApiVerifyEmailLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-code': {
      id: '/api/verify-code'
      path: '/api/verify-code'
      fullPath: '/api/verify-code'
      preLoaderRoute: typeof ApiVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-verification': {
      id: '/api/send-verification'
      path: '/api/send-verification'
      fullPath: '/api/send-verification'
      preLoaderRoute: typeof ApiSendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meal-plan': {
      id: '/api/meal-plan'
      path: '/api/meal-plan'
      fullPath: '/api/meal-plan'
      preLoaderRoute: typeof ApiMealPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-stream': {
      id: '/api/chat-stream'
      path: '/api/chat-stream'
      fullPath: '/api/chat-stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-image': {
      id: '/api/analyze-image'
      path: '/api/analyze-image'
      fullPath: '/api/analyze-image'
      preLoaderRoute: typeof ApiAnalyzeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-workout': {
      id: '/api/ai-workout'
      path: '/api/ai-workout'
      fullPath: '/api/ai-workout'
      preLoaderRoute: typeof ApiAiWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/treino/$id': {
      id: '/app/treino/$id'
      path: '/treino/$id'
      fullPath: '/app/treino/$id'
      preLoaderRoute: typeof AppTreinoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico/$id': {
      id: '/app/historico/$id'
      path: '/historico/$id'
      fullPath: '/app/historico/$id'
      preLoaderRoute: typeof AppHistoricoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exercicio/$id': {
      id: '/app/exercicio/$id'
      path: '/exercicio/$id'
      fullPath: '/app/exercicio/$id'
      preLoaderRoute: typeof AppExercicioIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCorpoRoute: typeof AppCorpoRoute
  AppExerciciosRoute: typeof AppExerciciosRoute
  AppNutricaoRoute: typeof AppNutricaoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppTreinosRoute: typeof AppTreinosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExercicioIdRoute: typeof AppExercicioIdRoute
  AppHistoricoIdRoute: typeof AppHistoricoIdRoute
  AppTreinoIdRoute: typeof AppTreinoIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCorpoRoute: AppCorpoRoute,
  AppExerciciosRoute: AppExerciciosRoute,
  AppNutricaoRoute: AppNutricaoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppTreinosRoute: AppTreinosRoute,
  AppIndexRoute: AppIndexRoute,
  AppExercicioIdRoute: AppExercicioIdRoute,
  AppHistoricoIdRoute: AppHistoricoIdRoute,
  AppTreinoIdRoute: AppTreinoIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingStepRoute: typeof OnboardingStepRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStepRoute: OnboardingStepRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CriarContaRoute: CriarContaRoute,
  EmailPendenteRoute: EmailPendenteRoute,
  LandingRoute: LandingRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PaywallRoute: PaywallRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  TermosRoute: TermosRoute,
  VerificarEmailRoute: VerificarEmailRoute,
  ApiAiWorkoutRoute: ApiAiWorkoutRoute,
  ApiAnalyzeImageRoute: ApiAnalyzeImageRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ApiMealPlanRoute: ApiMealPlanRoute,
  ApiSendVerificationRoute: ApiSendVerificationRoute,
  ApiVerifyCodeRoute: ApiVerifyCodeRoute,
  ApiVerifyEmailLinkRoute: ApiVerifyEmailLinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
